version: '3'
services:
  app:
    build: app/.
    volumes:
      - ./app/:/app/
    ports:
      - "5000:5000"
  db:
    image: "postgres"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: local
    ports:
      - "5432:5432"
